const PATTERNS = [
  {
    id: 'openai',
    name: 'OpenAI API Key',
    category: 'AI / ML',
    severity: 'critical',
    regex: /sk-[a-zA-Z0-9]{20,}/g,
  },
  {
    id: 'anthropic',
    name: 'Anthropic API Key',
    category: 'AI / ML',
    severity: 'critical',
    regex: /sk-ant-[a-zA-Z0-9]{20,}/g,
  },
  {
    id: 'google-ai',
    name: 'Google AI / Gemini API Key',
    category: 'AI / ML',
    severity: 'critical',
    regex: /AIza[0-9A-Za-z_-]{35}/g,
  },
  {
    id: 'huggingface',
    name: 'HuggingFace Access Token',
    category: 'AI / ML',
    severity: 'critical',
    regex: /hf_[A-Za-z0-9]{20,}/g,
  },
  {
    id: 'replicate',
    name: 'Replicate API Token',
    category: 'AI / ML',
    severity: 'critical',
    regex: /r8_[A-Za-z0-9]{20,}/g,
  },
  {
    id: 'aws-access-key',
    name: 'AWS Access Key ID',
    category: 'Cloud / Infrastructure',
    severity: 'critical',
    regex: /AKIA[0-9A-Z]{16}/g,
  },
  {
    id: 'aws-secret',
    name: 'AWS Secret Access Key',
    category: 'Cloud / Infrastructure',
    severity: 'critical',
    regex: /(aws_secret_access_key|aws_access_key_id)\s*[:=]\s*["'][A-Za-z0-9/+=]{20,}["']/gi,
  },
  {
    id: 'google-service-account',
    name: 'Google Service Account Key',
    category: 'Cloud / Infrastructure',
    severity: 'critical',
    regex: /"private_key"\s*:\s*"-----BEGIN PRIVATE KEY-----/g,
  },
  {
    id: 'firebase-config',
    name: 'Firebase Configuration',
    category: 'Cloud / Infrastructure',
    severity: 'high',
    regex: /firebaseConfig\s*=\s*\{[\s\S]{0,1000}?apiKey["']:\s*["']AIza[0-9A-Za-z_-]{35}[\s\S]{0,1000}?\}/g,
  },
  {
    id: 'github-token',
    name: 'GitHub Personal Access Token',
    category: 'Dev / SaaS',
    severity: 'critical',
    regex: /gh[pousr]_[A-Za-z0-9_]{36,}/g,
  },
  {
    id: 'gitlab-token',
    name: 'GitLab Personal Access Token',
    category: 'Dev / SaaS',
    severity: 'critical',
    regex: /glpat-[A-Za-z0-9_-]{20,}/g,
  },
  {
    id: 'stripe-live',
    name: 'Stripe Live Key',
    category: 'Dev / SaaS',
    severity: 'critical',
    regex: /(?:sk|pk)_live_[a-zA-Z0-9]{20,}/g,
  },
  {
    id: 'stripe-test',
    name: 'Stripe Test Key',
    category: 'Dev / SaaS',
    severity: 'low',
    regex: /(?:sk|pk)_test_[a-zA-Z0-9]{20,}/g,
  },
  {
    id: 'slack-token',
    name: 'Slack API Token',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /xox[baprs]-[A-Za-z0-9-]{10,}/g,
  },
  {
    id: 'discord-token',
    name: 'Discord Bot Token',
    category: 'Dev / SaaS',
    severity: 'critical',
    regex: /[A-Za-z0-9_-]{23,26}\.[A-Za-z0-9_-]{6,7}\.[A-Za-z0-9_-]{27,}/g,
  },
  {
    id: 'npm-token',
    name: 'NPM Access Token',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /npm_[A-Za-z0-9]{30,}/g,
  },
  {
    id: 'mapbox',
    name: 'Mapbox API Token',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /sk\.eyJ[A-Za-z0-9_-]{100,}/g,
  },
  {
    id: 'sentry-dsn',
    name: 'Sentry DSN',
    category: 'Dev / SaaS',
    severity: 'medium',
    regex: /https:\/\/[a-f0-9]{32}@o\d+\.ingest\.sentry\.io\/\d+/g,
  },
  {
    id: 'jwt',
    name: 'JWT Token Hardcoded',
    category: 'Generic / Hardcoded',
    severity: 'high',
    regex: /eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}/g,
  },
  {
    id: 'bearer-token',
    name: 'Bearer Token',
    category: 'Generic / Hardcoded',
    severity: 'high',
    regex: /Bearer\s+[A-Za-z0-9\-._~+/]{20,}={0,2}/g,
  },
  {
    id: 'private-key',
    name: 'Private Key Block',
    category: 'Generic / Hardcoded',
    severity: 'critical',
    regex: /-----BEGIN\s+(RSA|OPENSSH|EC|DSA|PGP)\s+PRIVATE\s+KEY-----/g,
  },
  {
    id: 'connection-string-mongo',
    name: 'MongoDB Connection String',
    category: 'Database',
    severity: 'critical',
    regex: /mongodb(?:\+srv)?:\/\/[^\s"']{10,}/g,
  },
  {
    id: 'connection-string-postgres',
    name: 'PostgreSQL Connection String',
    category: 'Database',
    severity: 'critical',
    regex: /postgres(?:ql)?:\/\/[^\s"']{10,}/g,
  },
  {
    id: 'connection-string-mysql',
    name: 'MySQL Connection String',
    category: 'Database',
    severity: 'critical',
    regex: /mysql:\/\/[^\s"']{10,}/g,
  },
  {
    id: 'connection-string-redis',
    name: 'Redis Connection String',
    category: 'Database',
    severity: 'high',
    regex: /redis:\/\/[^\s"']{10,}/g,
  },
  {
    id: 'hash-salt',
    name: 'Hash Salt / Rounds',
    category: 'Generic / Hardcoded',
    severity: 'medium',
    regex: /(salt|bcrypt|hash_rounds|pepper)\s*[:=]\s*["'][A-Za-z0-9$./]{8,}["']/gi,
  },
  {
    id: 'hardcoded-password',
    name: 'Hardcoded Password',
    category: 'Generic / Hardcoded',
    severity: 'high',
    regex: /(password|passwd|pwd)\s*[:=]\s*["'][^"'\s]{6,}["']/gi,
  },
  {
    id: 'generic-api-key',
    name: 'Generic API Key / Secret',
    category: 'Generic / Hardcoded',
    severity: 'medium',
    regex: /(api[_-]?key|api[_-]?secret|api_token|app_secret|client_secret|consumer_key|consumer_secret)\s*[:=]\s*["'][^"'\s]{8,}["']/gi,
  },
  {
    id: 'exposed-token',
    name: 'Exposed Token Variable',
    category: 'Generic / Hardcoded',
    severity: 'medium',
    regex: /(token|secret|credential|auth_key)\s*[:=]\s*["'][^"'\s]{8,}["']/gi,
  },
  {
    id: 'env-pattern',
    name: 'Environment Variable (KEY=VALUE)',
    category: 'Generic / Hardcoded',
    severity: 'high',
    regex: /(API_KEY|SECRET_KEY|SECRET|TOKEN|PASSWORD|PASSWD|DB_PASSWORD|DB_URL|DATABASE_URL|ACCESS_KEY|PRIVATE_KEY|AUTH_TOKEN|BEARER)\s*=\s*[^\s"']{6,}/gi,
  },
  {
    id: 'oauth-client-secret',
    name: 'OAuth Client Secret',
    category: 'Dev / SaaS',
    severity: 'critical',
    regex: /client_secret\s*[:=]\s*["'][A-Za-z0-9_-]{20,}["']/gi,
  },
  {
    id: 'twilio',
    name: 'Twilio API Credential',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /(twilio|account_sid|auth_token)\s*[:=]\s*["'][A-Za-z0-9]{20,}["']/gi,
  },
  {
    id: 'telegram-bot',
    name: 'Telegram Bot Token',
    category: 'Dev / SaaS',
    severity: 'critical',
    regex: /\b\d{8,10}:[A-Za-z0-9_-]{35,}\b/g,
  },
  {
    id: 'docker-hub',
    name: 'Docker Hub Credential',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /(docker_hub|dockerhub|docker_token|registry_token)\s*[:=]\s*["'][^"'\s]{8,}["']/gi,
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean PAT',
    category: 'Cloud / Infrastructure',
    severity: 'high',
    regex: /dop_v1_[a-f0-9]{64}/g,
  },
  {
    id: 'pulumi-token',
    name: 'Pulumi Access Token',
    category: 'Cloud / Infrastructure',
    severity: 'high',
    regex: /pul-[a-f0-9]{40}/g,
  },
  {
    id: 'git-credentials',
    name: 'Git Credentials in URL',
    category: 'Generic / Hardcoded',
    severity: 'critical',
    regex: /https?:\/\/[^:@\s]+:[^@\s]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?::\d{1,5})?(?:\/[^\s"')\]>]*)?/g,
  },
  {
    id: 'sendgrid',
    name: 'SendGrid API Key',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /SG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}/g,
  },
  {
    id: 'mailgun',
    name: 'Mailgun API Key',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /key-[a-f0-9]{32}/g,
  },
  {
    id: 'datadog',
    name: 'Datadog API Key',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /(datadog_api_key|dd_api_key|datadog_app_key)\s*[:=]\s*["'][A-Za-z0-9]{20,}["']/gi,
  },
  {
    id: 'newrelic',
    name: 'New Relic License Key',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /(new_relic_license_key|newrelic_license|newrelic_key)\s*[:=]\s*["'][A-Za-z0-9]{20,}["']/gi,
  },
  {
    id: 'algolia',
    name: 'Algolia API Key',
    category: 'Dev / SaaS',
    severity: 'high',
    regex: /(algolia_(api|admin|search)_key)\s*[:=]\s*["'][A-Za-z0-9]{20,}["']/gi,
  },
  {
    id: 'auth0',
    name: 'Auth0 Credential',
    category: 'Dev / SaaS',
    severity: 'medium',
    regex: /(auth0_(domain|client_id|client_secret|audience))\s*[:=]\s*["'][^"'\s]{5,}["']/gi,
  },

];

const ENDPOINT_PATHS = [
  '/.env',
  '/env',
  '/.env.local',
  '/.env.production',
  '/.env.development',
  '/.env.staging',
  '/config.json',
  '/config.js',
  '/config',
  '/credentials.json',
  '/credentials',
  '/secret',
  '/secrets',
  '/secret.json',
  '/admin',
  '/debug',
  '/backup',
  '/backup.zip',
  '/backup.tar.gz',
  '/db',
  '/database',
  '/database.json',
  '/api-keys',
  '/keys',
  '/keys.json',
  '/tokens',
  '/tokens.json',
  '/.git/config',
  '/.git/HEAD',
  '/.gitignore',
  '/.htaccess',
  '/.aws/credentials',
  '/.azure/credentials',
  '/.npmrc',
  '/.dockercfg',
  '/Dockerfile',
  '/docker-compose.yml',
  '/docker-compose.yaml',
  '/package.json',
  '/composer.json',
  '/wp-config.php',
  '/config.php',
  '/settings.php',
  '/robots.txt',
  '/sitemap.xml',
  '/crossdomain.xml',
  '/client_secrets.json',
  '/service_account.json',
  '/terraform.tfvars',
  '/terraform.tfstate',
  '/.terraform',
  '/s3crets',
  '/swagger.json',
  '/swagger.yaml',
  '/openapi.json',
  '/graphql',
  '/.well-known/security.txt',
];

const STORAGE_KEY_PATTERNS = [
  /(?:bearer|auth|credential|password|jwt|token|secret)/i,
  /(?:api[._-]?key|private[._-]?key|access[._-]?token|refresh[._-]?token|session)/i,
  /(firebase|stripe|slack|discord|openai|aws)/i,
];

const STORAGE_KEY_EXCLUSIONS = [
  /^ref-selector:/,
  /^COPILOT_LAST_USED_/i,
  /^gist-/,
  /^github-/i,
  /^codepilot_/i,
];
